version: '3.7ß'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: docker-from-zero-frontend
    command: serve -s build -l 3000
    restart: unless-stopped
    environment:
      - WDS_SOCKET_PORT=0
    networks:
      - focus-lines-network

  api:
    build: ./api
    container_name: focus-lines-api
    restart: on-failure
    volumes:
      - ./api:/usr/src/app
    links:
      - api_db
    environment:
      - DB_HOST=api-db
    depends_on:
      - api_db
    ports:
      - "5000:5000"
    networks:
      - focus-lines-network

  api_db:
    build: ./api-db
    command: --default-authentication-plugin=caching_sha2_password
    container_name: focus-lines-api-db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - api_db:/var/lib/mysql
    networks:
      - focus-lines-network

  nginx:
    image: nginx:stable-alpine
    container_name: focus-lines-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
    networks:
      - focus-lines-network

volumes:
  api_db:

networks:
  focus-lines-network:
    driver: bridge
